#remap prefix from ctrl-b to -a
set -g status off
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
set -g status-style bg=default
set-option -g status 2 # this is here so that our dumb BIG icons have room.

# split panes using | and -
unbind z
unbind x
bind z split-window -h
bind x split-window -v
bind e kill-pane

# switch panes using Alt-arrow without prefix
#bind -n Super_L-h select-pane -L
#bind -n Super_L-l select-pane -R
bind -n C-o run-shell "tmux previous-window"
bind -n C-p run-shell "tmux next-window"
bind -n C-s run-shell "tmux set -g status; tmux set-option -g status 2"
bind -n C-h run-shell "tmux set -g status off"
bind -n C-b source-file ~/.tmux.conf
bind -n M-r copy-mode
bind -n C-l send-keys :reload enter

set -sg escape-time 0

set-option -sa terminal-features ',xterm-256color:RGB'
set-option -ga terminal-features ",xterm-256color:usstyle"
set-option -ga terminal-overrides ',xterm-256color:Tc'
set -g default-terminal "xterm-256color"

set-option -g status-interval 1
set-option -g status-position top
set-option -g window-status-format '#[fg=colour62,bg=default]#[bg=colour62, fg=colour3]#W #[fg=colour63,bg=colour62]#[fg=colour63,bg=default] #[fg=colour3]  #[fg=colour63] '
set-option -g window-status-current-format '#[fg=colour6,bg=default]#[bg=colour6, fg=colour63]#W #[fg=colour63,bg=colour6]#[fg=colour63,bg=default] #[fg=colour6] '
set-option -g window-status-separator ' '
set-option -g status-left-length 20
set-option -g status-justify left
#
set-option -g status-left '#[fg=colour3, bg=colour63]     #[bg=default fg=colour63]#[fg=colour3] '
set-option -g status-format[1] "#[fg=colour63, bg=default]#[bg=colour63]     #[bg=default]"
set -g status-right "#[fg=colour63]#[fg=colour62]#[fg=2,bg=colour62]󱎘  #[fg=6,bg=colour62]  #[fg=7,bg=colour62]󰳳 #[fg=colour62, bg=default]"

set-option -g display-panes-colour default
set-option -g display-panes-active-colour default
set-option -g focus-events on

set-option -g update-environment "WAYLAND_DISPLAY NIRI_SOCKET"

