#######################################################################
#                                                                     #
# modded xero conf by zoefiri                                — ▭ ✖    #
#                                                                     #
#######################################################################
#                                                                     #
#      ,####  ,##.    #######,                                ,,,,    #
#     ###### ######   #########,  ,####,         ,,,,,,,,########'    #
#    ,##' #### '###  ,###    ###  #######,      #########''  '#'      #
#    ###  ###   ###  #####   ###  ##, '###          '#       ,#       #
#    ##' ,###  ###   ##########'  ###   ##          ,#   ,#####       #   
#    ##  ###  ###    ###''####'   ###, ,##      ,#####   #####'       #
#    '#  ##'  '##    ###          ########      #####'   '###'        #
#                    #'           #######'      '###'                 #
#                                                                     #
#######################################################################




# files #
#music_directory      "~/music"
music_directory       "~/music"
playlist_directory    "~/.mpd/playlists"
db_file               "~/.mpd/mpd.db"
log_file              "~/.mpd/log"
pid_file              "~/.mpd/pid"
state_file            "~/.mpd/state"


# opts #
bind_to_address      "127.0.0.1"
port                 "6600"
log_level            "default"
max_connections      "100"
filesystem_charset   "UTF-8"


# visualizer + audio output #
audio_output {
   type   "pipewire"
   name   "PipeWire Sound Server"
}
audio_output {
   type		"fifo"
   name		"visualizer"
   path		"/tmp/mpd.fifo"
   format	"44100:16:2"
}


