#################################
#             Corners           #
#################################
# requires: https://github.com/sdhand/compton
corner-radius = 9.0;
round-borders = 10;
rounded-corners-exclude = [
   "window_type = 'dock'"
];

rules = (
   { match = "class_i = 'ghostty'"; opacity = 1.0; }
);
#wintypes:
#{
#   dock = { shadow = true; }
#}
#shadow-offset-x = 7
#shadow-offset-y = 7
#shadow-radius = 0


#################################
#       General Settings        #
#################################
animations=true

blur: {
   method = "dual_kawase";
   strength = 2.95;
}

blur-background-exclude = [
   "class_g = 'eww-bottri'",
   "class_g = 'eww-batwin'",
   "class_g = 'eww-spaces'",
   "class_g = 'eww-paraspaces'",
   "class_g = 'eww-mhead'",
   "class_g = 'eww-datehour'",
   "class_g = 'eww-vol'",
   "class_g = 'eww-ram'",
];

# Daemonize process. Fork to background after initialization. Causes issues with certain (badly-written) drivers.
# daemon = false

# Specify the backend to use: `xrender`, `glx`, or `xr_glx_hybrid`.
# `xrender` is the default one.
#
experimental-backends = true;
backend = "glx";
#backend = "xrender";


# Enable/disable VSync.
# vsync = false
vsync = true


animations = (
      {
      triggers = [ "close" ];
      preset = "disappear";
      duration = 0.19;
      },
      {
      triggers = [ "hide" ];
      preset = "fly-out";
      direction = "down";
      duration = 0.07;
      },
      {
      triggers = [ "open", "show"];
      preset = "appear";
      curve = "cubic-bezier(0.25, 0.1, 0.25, 1.0)";
      direction = "right";
      duration = 0.09;
      },
      {
      triggers = [ "geometry" ];
      preset = "geometry-change";
      duration = 0.09;
      saved-image-blend = 1;
      },

      )
