#!/bin/bash

##########
# volume #
##########
vol(){
   while true; do
      cat /tmp/dacvol | xargs printf "%%{cT1}%d %%{T2}\n"
   done
}


###########
# battery #
###########
bat(){
   while true; do
      read bat < "/sys/class/power_supply/BAT0/capacity"
      printf "%%{c}%d \n" $bat
      sleep 2
   done
}


###############
# date + time #
###############
datetime(){
   while true; do
      date +"%%{c}%H//%M   %m//%d " 
      sleep 3
   done
}


##############
# workspaces #
##############
herbspaces2(){
WORKSPACES=7 # make this number the amount of workspaces you want to display
read yellow < /home/zoe/.config/ricer/ricer/ricer/ricertemplates/colors/base10
read green < /home/zoe/.config/ricer/ricer/ricer/ricertemplates/colors/base11

getinfo(){
    wspaces=$(wmctrl -d | head -$workspaces | grep -o "[0-9]  [-\*]" | rev | tr '\n' ' ' | cut -d '-' -f 1-7)
}


format(){
    echo "$wspaces" | sed\
        -e 's/0//'\
        -e 's/1//'\
        -e 's/2//'\
        -e 's/3//'\
        -e 's/4//'\
        -e 's/5//'\
        -e 's/6//'\
        -e "s/\-/%\{F#$red\}/g"\
        -e "s/\*  /  %\{F#$lblue\}/g"
    }

change(){
    cat < /tmp/herbchange
}

mkfifo /tmp/herbchange
while true;
do
    getinfo
    format
    change
done
}

################
# bar settings #
################
read red < /home/zoe/.config/ricer/ricertemplates/colors/base8
read orange < /home/zoe/.config/ricer/ricertemplates/colors/base9
read yellow < /home/zoe/.config/ricer/ricertemplates/colors/base10
read green < /home/zoe/.config/ricer/ricertemplates/colors/base11
read lblue < /home/zoe/.config/ricer/ricertemplates/colors/base12
read blue < /home/zoe/.config/ricer/ricertemplates/colors/base13
read brown < /home/zoe/.config/ricer/ricertemplates/colors/base14
read background < /home/zoe/.config/ricer/ricertemplates/colors/base0
read background2 < /home/zoe/.config/ricer/ricertemplates/colors/base1
font="Lexend Deca:size=14:style=Medium"
icons1="Font Awesome 5 Free Solid:size=15"
icons2="Symbols Nerd Font:size=12"
echo $background IS TEST COLOR
trap "kill %1; kill %2; kill %3; kill %4; kill %5" SIGINT SIGTERM


################
# DISPLAY BARS #
################
#bkg
echo | lemonbar -B "#$background2" -g 808x58+560+1013 -p &
sleep .1
echo | lemonbar -B "#$background" -g 800x50+564+1017 -p &


#workspaces
herbspaces2 | lemonbar -o 1 -f "$icons1" -o -2 -f "$icons2" -g 225x41+848+1019 -B"#$background" &

#volume
vol | lemonbar -o 0 -f "$font" -o -2 -f "$icons2" -g 86x41+615+1019 -B"#$background" -F"#$red" &

#date
datetime | lemonbar -o 0 -f "$font" -o -2 -f "$icons2" -g 200x41+1100+1019 -B"#$background" -F"#$red" &

#battery
bat | lemonbar -p -o 0 -f "$font" -o -2 -f "$icons2" -g 84x41+725+1019 -B"#$background" -F"#$red" 

