#!/bin/bash
hc() {
   herbstclient "$@"
}
sleep 1

##############
# set modkey #
##############
Mod=Mod4   

################################
# programs and script triggers #
################################
#volume
hc keybind $Mod-n spawn DACvol 0
hc keybind $Mod-m spawn DACvol 1

#brightness
hc keybind $Mod-F9 spawn xbacklight -inc -10
hc keybind $Mod-F10 spawn xbacklight -inc +10

#rofi
hc keybind $Mod-d spawn rofi -show run -location 0 -lines 5 -bw 0 -columns 2 -width 10 -display-run ">"
hc keybind $Mod-c spawn rofi -modi "clipboard:greenclip print" -show clipboard -run-command '{cmd}' -location 0 -lines 5 -bw 0 -font "kakwafont 9"
hc keybind $Mod-e spawn /home/zoe/bin/emote

#bind catching
hc keybind $Mod-q echo "haha no."
hc keybind Ctrl-q spawn echo "reee no."

#spawn scratchpad
hc keybind $Mod-i spawn scratchpad 2
hc keybind $Mod-Shift-i spawn scratchpad +2

#screencap
hc keybind $Mod-w spawn flameshot gui

#lock up
hc keybind Ctrl-Alt-l spawn bash /bin/glock

#close window
hc keybind $Mod-Shift-q close
hc keybind $Mod-q spawn /home/zoe/bin/herbkiller
hc keybind $Mod-Shift-r reload

#spawn terminal
hc keybind $Mod-Return spawn alacritty
hc keybind $Mod-Shift-Return spawn st

#fix mouse
hc keybind $Mod-t spawn mousefix

#alacritty transparency
hc keybind $Mod-semicolon spawn alactrans d
hc keybind $Mod-apostrophe spawn alactrans i

############
# wm binds #
############

##################
# basic movement #
##################
# focusing clients
hc keybind $Mod-Left  focus left
hc keybind $Mod-Down  focus down
hc keybind $Mod-Up    focus up
hc keybind $Mod-Right focus right
hc keybind $Mod-h     focus left
hc keybind $Mod-j     focus down
hc keybind $Mod-k     focus up
hc keybind $Mod-l     focus right

# moving clients
hc keybind $Mod-Shift-Left  shift left
hc keybind $Mod-Shift-Down  shift down
hc keybind $Mod-Shift-Up    shift up
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-h     shift left
hc keybind $Mod-Shift-j     shift down
hc keybind $Mod-Shift-k     shift up
hc keybind $Mod-Shift-l     shift right

# framesplitting
hc keybind $Mod-u       split   bottom  0.5
hc keybind $Mod-o       split   right   0.5
hc keybind $Mod-r remove


# let the current frame explode into subframes
hc keybind $Mod-Control-space split explode

# resizing frames
resizestep=0.015
hc keybind $Mod-Control-h       resize left +$resizestep
hc keybind $Mod-Control-j       resize down +$resizestep
hc keybind $Mod-Control-k       resize up +$resizestep
hc keybind $Mod-Control-l       resize right +$resizestep
hc keybind $Mod-Control-Left    resize left +$resizestep
hc keybind $Mod-Control-Down    resize down +$resizestep
hc keybind $Mod-Control-Up      resize up +$resizestep
hc keybind $Mod-Control-Right   resize right +$resizestep

# resizing windows
hc keybind $Mod-Alt-h spawn ~/bin/herbsize -x
hc keybind $Mod-Alt-j spawn ~/bin/herbsize -y
hc keybind $Mod-Alt-k spawn ~/bin/herbsize +y
hc keybind $Mod-Alt-l spawn ~/bin/herbsize +x

##############
# workspaces #
##############
for i in {0..8}
do
   hc add "$i"
   hc keybind $Mod-"$((i+1))" spawn herbswitcher "$i"
   hc keybind "$Mod-Shift-$((i+1))" move_index $i  
done

# cycle workspaces
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible

# special workspaces
hc add settings
hc add vid
hc rule --class=Pavucontrol --tag=settings --focus=off
hc spawn pavucontrol
hc keybind $Mod-a use settings
hc keybind $Mod-v use vid
hc keybind $Mod-Shift-v move vid


#################
# window states #
#################
hc keybind $Mod-s floating toggle
hc keybind $Mod-Shift-s attr clients.focus.floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-p pseudotile toggle
# The following cycles through the available layouts within a frame, but skips
# layouts, if the layout change wouldn't affect the actual window positions.
# I.e. if there are two windows within a frame, the grid layout is skipped.
hc keybind $Mod-space                                                           \
   or , and . compare tags.focus.curframe_wcount = 2                   \
   . cycle_layout +1 vertical horizontal max vertical grid    \
   , cycle_layout +1

####################################
# mouse + monitor + floating binds #
####################################
# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 zoom
hc mousebind $Mod-Button3 resize

# focus
hc keybind $Mod-BackSpace   cycle_monitor
hc keybind $Mod-Tab         cycle +1
hc keybind $Mod-Shift-Tab   cycle -1


