#!/bin/sh

echo we did it ma! >> /tmp/guweh
bspc monitor -d 1 2 3 4 5 6 7 8 9 I0

#-pretty things
#
####-colors
   #--,
   read bg < /home/zoe/.config/ricer/ricertemplates/colors/base0
   read ca1 < /home/zoe/.config/ricer/ricertemplates/colors/base1
   read ca2 < /home/zoe/.config/ricer/ricertemplates/colors/base2
   read ca3 < /home/zoe/.config/ricer/ricertemplates/colors/base3
   read ca4 < /home/zoe/.config/ricer/ricertemplates/colors/base4
   read ca5 < /home/zoe/.config/ricer/ricertemplates/colors/base5
   read ca6 < /home/zoe/.config/ricer/ricertemplates/colors/base6
   read c1 < /home/zoe/.config/ricer/ricertemplates/colors/base7
   read c2 < /home/zoe/.config/ricer/ricertemplates/colors/base8
   read c3 < /home/zoe/.config/ricer/ricertemplates/colors/base9
   read c4 < /home/zoe/.config/ricer/ricertemplates/colors/base10
   read c5 < /home/zoe/.config/ricer/ricertemplates/colors/base11
   read c6 < /home/zoe/.config/ricer/ricertemplates/colors/base12
   read c7 < /home/zoe/.config/ricer/ricertemplates/colors/base13
   read c8 < /home/zoe/.config/ricer/ricertemplates/colors/base14
   read c9 < /home/zoe/.config/ricer/ricertemplates/colors/base15

   #theming
   #--,
      bspc config focused_border_color            "#$c1"
      bspc config active_border_color             "#$c2"
      bspc config normal_border_color             "#$c3"
      bspc config urgent_border_color             "#$c4"
      bspc config presel_feedback_color           "#$c5"
      echo bspc config normal_border_color		"#$ca4" >> /tmp/guweh
      echo bspc config active_border_color		"#$c1"  >> /tmp/guweh
      echo bspc config focused_border_color	   "#$c4"  >> /tmp/guweh
      echo bspc config presel_feedback_color	"#$bg"     >> /tmp/guweh

      bspc config border_width      06
      bspc config border_radius     20
      bspc config window_gap        20
      bspc config top_padding       35
      bspc config right_padding     15
      bspc config bottom_padding    15
      bspc config left_padding      15
      bspc config ignore_ewmh_struts true

#tiling stuff
#--,
   bspc config split_ratio                 0.50
   bspc config borderless_monocle          true
   bspc config gapless_monocle             true
   bspc config focus_follows_pointer       true
   bspc config history_aware_focus         true


# startup
####--------- program list ---------
   set -- 'sxhkd -c '"$HOME"'/.config/sxhkd/sxhkdrc' lemon plugitinfucker keebdisable 'greenclip daemon' keynav picom 'flashfocus -o 0.75' chargeindicator wallserver 
   
   #-kill previous instances of stuff
   #--,
      for program do 
         pkill "$(echo $program | cut -d ' ' -f1)" 
      done

   #-startup programs
   #--,
      for program do 
         $program & 
      done

   #- one-offs
   #--,
      xset b off 
      walc r 
      xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Disable While Typing Enabled" 0

echo we REALLY we did it ma! >> /tmp/guweh
