#!/bin/bash
# scripts
#[ -z $1 ] && $0 f | while read -r line; do eval "${line}" ; done
#if [ $1 = f ]
#then
vol(){
        $HOME/.config/lemons/vol
}
bat(){
    $HOME/.config/lemons/bat
}
date(){
    $HOME/.config/lemons/date
}
herbspaces2(){
    $HOME/.config/lemons/herbspaces2
}
keeb(){
    $HOME/.config/lemons/keeb
}

red="#e35142"
orange="#fba11b"
yellow="#f2ff27"
green="#5ceb5a"
lblue="#5aebbc"
blue="#489bf0"
brown="#FF9742"
background="#1c1810"
background2="#272538"
font="Operator Mono:size=15:style=Italic"
icons1="Font Awesome 5 Free Solid:size=15"
icons2="Symbols Nerd Font:size=18"


    #bars

        #workspaces
        herbspaces2 | lemonbar -o -4 -f "$icons1" -o 0 -f "$icons2" -g 310x41+1588+1022 -B"$background" &

        #volume
        vol | lemonbar -o 0 -f "$font" -f "$icons1" -g 86x41+17+1022 -B"$background" -F"$green" &

        #date
        date | lemonbar -o 0 -f "$font" -f "$icons1" -g 240x41+270+1022 -B"$background" -F"$red" &

        #battery
        bat | lemonbar -o 0 -f "$font" -f "$icons1" -g 84x41+145+1022 -B"$background" -F"$orange" &

        #keeb
        keeb | lemonbar -p -o 0 -f "$font" -f "$icons2" -g 50x41+1497+1022 -B"$background" -F"$lblue" &


        echo | lemonbar -p -g 100x56+10+1014 -B"$background" &
        echo | lemonbar -p -g 325x56+1580+1014 -B"$background" &
        echo | lemonbar -p -g 254x56+263+1014 -B"$background" &
        echo | lemonbar -p -g 100x56+137+1014 -B"$background" &
        echo | lemonbar -p -g 66x56+1490+1014 -B"$background" &
#    fi
