local M = {}
M.methods = {}


function M.setup()
   local sel_bg = 'sbg'
   local sel_fg = 'sfg'
   local norm_bg = 'ibg'
   local norm_fg = 'ifg'
   local bg = 'null'

   local basic = {}

   local tabline_template = {}

   local default = {
      filetypes={'default'},
      active={
      },
      inactive={
      }
   }

   local explorer = {
      filetypes = {'fern', 'NvimTree','netrw'},
      active = {
         {' ', {'white', 'black'} },
      },
      --- show active components when the window is inactive
      always_active = true,
      --- It will display a last window statusline even that window should inactive
      show_last_status = true
   }



   local windline = require('windline')
   windline.setup({
      colors_name = function(colors)
         -- print(vim.inspect(colors))
         -- ADD MORE COLOR HERE ----
         colors.DevIconDiff                =     59
         colors.DevIconElm                 =     67
         colors.DevIconJl                  =     133
         colors.DevIconSass                =     204
         colors.DevIconXcPlayground        =     173
         colors.DevIconSln                 =     98
         colors.DevIconTxt                 =     113
         colors.DevIconTcl                 =     67
         colors.DevIconR                   =     65
         colors.DevIconZshrc               =     113
         colors.DevIconTex                 =     58
         colors.DevIconLua                 =     74
         colors.DevIconJsx                 =     67
         colors.DevIconJson                =     185
         colors.DevIconGif                 =     140
         colors.DevIconMl                  =     173
         colors.DevIconMarkdown            =     67
         colors.DevIconCp                  =     67
         colors.DevIconRmd                 =     67
         colors.DevIconBrewfile            =     52
         colors.DevIconZsh                 =     113
         colors.DevIconVerilog             =     29
         colors.DevIconCrystal             =     16
         colors.DevIconJpg                 =     140
         colors.DevIconSystemVerilog       =     29
         colors.DevIconPyc                 =     67
         colors.DevIconGitCommit           =     59
         colors.DevIconIco                 =     185
         colors.DevIconProcfile            =     140
         colors.DevIconDesktopEntry        =     60
         colors.DevIconFsscript            =     67
         colors.DevIconKotlin              =     208
         colors.DevIconSig                 =     173
         colors.DevIconZig                 =     208
         colors.DevIconKotlinScript        =     208
         colors.DevIconEx                  =     140
         colors.DevIconMli                 =     173
         colors.DevIconSvelte              =     202
         colors.DevIconSql                 =     188
         colors.DevIconC                   =     75
         colors.DevIconEjs                 =     185
         colors.DevIconJava                =     167
         colors.DevIconGruntfile           =     173
         colors.DevIconSvg                 =     215
         colors.DevIconXul                 =     173
         colors.DevIconDart                =     25
         colors.DevIconCMake               =     66
         colors.DevIconZshenv              =     113
         colors.DevIconHxx                 =     140
         colors.DevIconYaml                =     66
         colors.DevIconCobol               =     25
         colors.DevIconCPlusPlus           =     204
         colors.DevIconDefault             =     66
         colors.DevIconGo                  =     67
         colors.DevIconGitLogo             =     202
         colors.DevIconJpeg                =     140
         colors.DevIconVimrc               =     29
         colors.DevIconHtml                =     166
         colors.DevIconIni                 =     66
         colors.DevIconCpp                 =     67
         colors.DevIconHtm                 =     166
         colors.DevIconDoc                 =     25
         colors.DevIconScss                =     204
         colors.DevIconGitConfig           =     59
         colors.DevIconSwift               =     173
         colors.DevIconKsh                 =     59
         colors.DevIconLess                =     60
         colors.DevIconGitModules          =     59
         colors.DevIconGemspec             =     52
         colors.DevIconStyl                =     107
         colors.DevIconBmp                 =     140
         colors.DevIconGodotProject        =     66
         colors.DevIconLhs                 =     140
         colors.DevIconD                   =     64
         colors.DevIconVim                 =     29
         colors.DevIconScala               =     167
         colors.DevIconTerminal            =     71
         colors.DevIconGemfile             =     52
         colors.DevIconClojureC            =     107
         colors.DevIconFsx                 =     67
         colors.DevIconTs                  =     67
         colors.DevIconHpp                 =     140
         colors.DevIconRlib                =     180
         colors.DevIconCoffee              =     185
         colors.DevIconLicense             =     185
         colors.DevIconAi                  =     185
         colors.DevIconGitAttributes       =     59
         colors.DevIconBashProfile         =     113
         colors.DevIconSolidity            =     67
         colors.DevIconVagrantfile         =     27
         colors.DevIconToml                =     66
         colors.DevIconDockerfile          =     59
         colors.DevIconFsharp              =     67
         colors.DevIconClojureDart         =     67
         colors.DevIconHaml                =     188
         colors.DevIconNPMIgnore           =     161
         colors.DevIconConfiguration       =     231
         colors.DevIconEex                 =     140
         colors.DevIconErb                 =     52
         colors.DevIconXls                 =     23
         colors.DevIconAwk                 =     59
         colors.DevIconYml                 =     66
         colors.DevIconXml                 =     173
         colors.DevIconNix                 =     110
         colors.DevIconGvimrc              =     29
         colors.DevIconErl                 =     132
         colors.DevIconClojureJS           =     67
         colors.DevIconRs                  =     180
         colors.DevIconPhp                 =     140
         colors.DevIconTwig                =     107
         colors.DevIconMjs                 =     221
         colors.DevIconSml                 =     173
         colors.DevIconSlim                =     166
         colors.DevIconHeex                =     140
         colors.DevIconMdx                 =     67
         colors.DevIconFs                  =     67
         colors.DevIconCson                =     185
         colors.DevIconDsStore             =     59
         colors.DevIconPromptPs1           =     59
         colors.DevIconMotoko              =     99
         colors.DevIconMixLock             =     140
         colors.DevIconDropbox             =     27
         colors.DevIconProlog              =     179
         colors.DevIconH                   =     140
         colors.DevIconRss                 =     215
         colors.DevIconCs                  =     58
         colors.DevIconExs                 =     140
         colors.DevIconFavicon             =     185
         colors.DevIconBat                 =     154
         colors.DevIconDrools              =     217
         colors.DevIconJs                  =     185
         colors.DevIconVue                 =     107
         colors.DevIconHs                  =     140
         colors.DevIconPng                 =     140
         colors.DevIconPm                  =     67
         colors.DevIconBinaryGLTF          =     215
         colors.DevIconRproj               =     65
         colors.DevIconDump                =     188
         colors.DevIconDb                  =     188
         colors.DevIconCss                 =     60
         colors.DevIconPy                  =     61
         colors.DevIconPsb                 =     67
         colors.DevIconTextResource        =     185
         colors.DevIconSettingsJson        =     98
         colors.DevIconPl                  =     67
         colors.DevIconConfigRu            =     52
         colors.DevIconNim                 =     220
         colors.DevIconConf                =     66
         colors.DevIconRake                =     52
         colors.DevIconWebmanifest         =     221
         colors.DevIconOpenTypeFont        =     231
         colors.DevIconClojure             =     107
         colors.DevIconMaterial            =     132
         colors.DevIconCxx                 =     67
         colors.DevIconVHDL                =     29
         colors.DevIconLeex                =     140
         colors.DevIconMint                =     108
         colors.DevIconMustache            =     173
         colors.DevIconNodeModules         =     161
         colors.DevIconOPUS                =     208
         colors.DevIconBash                =     113
         colors.DevIconZshprofile          =     113
         colors.DevIconWebp                =     140
         colors.DevIconGDScript            =     66
         colors.DevIconGitIgnore           =     59
         colors.DevIconPsd                 =     67
         colors.DevIconBabelrc             =     185
         colors.DevIconHrl                 =     132
         colors.DevIconPdf                 =     124
         colors.DevIconPpt                 =     167
         colors.DevIconRb                  =     52
         colors.DevIconGitlabCI            =     166
         colors.DevIconRakefile            =     52
         colors.DevIconBashrc              =     113
         colors.DevIconWebpack             =     67
         colors.DevIconGulpfile            =     167
         colors.DevIconSuo                 =     98
         colors.DevIconMakefile            =     66
         colors.DevIconHh                  =     140
         colors.DevIconCsv                 =     113
         colors.DevIconPyo                 =     67
         colors.DevIconNPMrc               =     161
         colors.DevIconMd                  =     67
         colors.DevIconTextScene           =     140
         colors.DevIconCsh                 =     59
         colors.DevIconFish                =     59
         colors.DevIconCMakeLists          =     66
         colors.DevIconFsi                 =     67
         colors.DevIconTor                 =     67
         colors.DevIconEdn                 =     67
         colors.DevIconPackedResource      =     66
         colors.DevIconSh                  =     59
         colors.DevIconFennel              =     230
         colors.DevIconHbs                 =     208
         colors.DevIconPyd                 =     67
         colors.DevIconTsx                 =     67
         colors.test = 63
         colors.c0 = 0
         colors.c1 = 60
         colors.c2 = 61
         colors.c3 = 62
         colors.c4 = 63
         colors.c5 = 64
         colors.c6 = 65
         colors.c7 = 1
         colors.c8 = 2
         colors.c9 = 3
         colors.c10 = 4
         colors.c11 = 5
         colors.c12 = 6
         colors.cs = 67

         return colors
      end,
      statuslines = {
         explorer, {require('plugconfs.windline-custom-theme')}
      },
      tabline = {
         template = {
            -- this use a highlight color a text will replace by tab name
            DevIconDiff                 = {'', {'DevIconDiff'                , sel_bg}},
            DevIconElm                  = {'', {'DevIconElm'                 , sel_bg}},
            DevIconJl                   = {'', {'DevIconJl'                  , sel_bg}},
            DevIconSass                 = {'', {'DevIconSass'                , sel_bg}},
            DevIconXcPlayground         = {'', {'DevIconXcPlayground'        , sel_bg}},
            DevIconSln                  = {'', {'DevIconSln'                 , sel_bg}},
            DevIconTxt                  = {'', {'DevIconTxt'                 , sel_bg}},
            DevIconTcl                  = {'', {'DevIconTcl'                 , sel_bg}},
            DevIconR                    = {'', {'DevIconR'                   , sel_bg}},
            DevIconZshrc                = {'', {'DevIconZshrc'               , sel_bg}},
            DevIconTex                  = {'', {'DevIconTex'                 , sel_bg}},
            DevIconLua                  = {'', {'DevIconLua'                 , sel_bg}},
            DevIconJsx                  = {'', {'DevIconJsx'                 , sel_bg}},
            DevIconJson                 = {'', {'DevIconJson'                , sel_bg}},
            DevIconGif                  = {'', {'DevIconGif'                 , sel_bg}},
            DevIconMl                   = {'', {'DevIconMl'                  , sel_bg}},
            DevIconMarkdown             = {'', {'DevIconMarkdown'            , sel_bg}},
            DevIconCp                   = {'', {'DevIconCp'                  , sel_bg}},
            DevIconRmd                  = {'', {'DevIconRmd'                 , sel_bg}},
            DevIconBrewfile             = {'', {'DevIconBrewfile'            , sel_bg}},
            DevIconZsh                  = {'', {'DevIconZsh'                 , sel_bg}},
            DevIconVerilog              = {'', {'DevIconVerilog'             , sel_bg}},
            DevIconCrystal              = {'', {'DevIconCrystal'             , sel_bg}},
            DevIconJpg                  = {'', {'DevIconJpg'                 , sel_bg}},
            DevIconSystemVerilog        = {'', {'DevIconSystemVerilog'       , sel_bg}},
            DevIconPyc                  = {'', {'DevIconPyc'                 , sel_bg}},
            DevIconGitCommit            = {'', {'DevIconGitCommit'           , sel_bg}},
            DevIconIco                  = {'', {'DevIconIco'                 , sel_bg}},
            DevIconProcfile             = {'', {'DevIconProcfile'            , sel_bg}},
            DevIconDesktopEntry         = {'', {'DevIconDesktopEntry'        , sel_bg}},
            DevIconFsscript             = {'', {'DevIconFsscript'            , sel_bg}},
            DevIconKotlin               = {'', {'DevIconKotlin'              , sel_bg}},
            DevIconSig                  = {'', {'DevIconSig'                 , sel_bg}},
            DevIconZig                  = {'', {'DevIconZig'                 , sel_bg}},
            DevIconKotlinScript         = {'', {'DevIconKotlinScript'        , sel_bg}},
            DevIconEx                   = {'', {'DevIconEx'                  , sel_bg}},
            DevIconMli                  = {'', {'DevIconMli'                 , sel_bg}},
            DevIconSvelte               = {'', {'DevIconSvelte'              , sel_bg}},
            DevIconSql                  = {'', {'DevIconSql'                 , sel_bg}},
            DevIconC                    = {'', {'DevIconC'                   , sel_bg}},
            DevIconEjs                  = {'', {'DevIconEjs'                 , sel_bg}},
            DevIconJava                 = {'', {'DevIconJava'                , sel_bg}},
            DevIconGruntfile            = {'', {'DevIconGruntfile'           , sel_bg}},
            DevIconSvg                  = {'', {'DevIconSvg'                 , sel_bg}},
            DevIconXul                  = {'', {'DevIconXul'                 , sel_bg}},
            DevIconDart                 = {'', {'DevIconDart'                , sel_bg}},
            DevIconCMake                = {'', {'DevIconCMake'               , sel_bg}},
            DevIconZshenv               = {'', {'DevIconZshenv'              , sel_bg}},
            DevIconHxx                  = {'', {'DevIconHxx'                 , sel_bg}},
            DevIconYaml                 = {'', {'DevIconYaml'                , sel_bg}},
            DevIconCobol                = {'', {'DevIconCobol'               , sel_bg}},
            DevIconCPlusPlus            = {'', {'DevIconCPlusPlus'           , sel_bg}},
            DevIconDefault              = {'', {'DevIconDefault'             , sel_bg}},
            DevIconGo                   = {'', {'DevIconGo'                  , sel_bg}},
            DevIconGitLogo              = {'', {'DevIconGitLogo'             , sel_bg}},
            DevIconJpeg                 = {'', {'DevIconJpeg'                , sel_bg}},
            DevIconVimrc                = {'', {'DevIconVimrc'               , sel_bg}},
            DevIconHtml                 = {'', {'DevIconHtml'                , sel_bg}},
            DevIconIni                  = {'', {'DevIconIni'                 , sel_bg}},
            DevIconCpp                  = {'', {'DevIconCpp'                 , sel_bg}},
            DevIconHtm                  = {'', {'DevIconHtm'                 , sel_bg}},
            DevIconDoc                  = {'', {'DevIconDoc'                 , sel_bg}},
            DevIconScss                 = {'', {'DevIconScss'                , sel_bg}},
            DevIconGitConfig            = {'', {'DevIconGitConfig'           , sel_bg}},
            DevIconSwift                = {'', {'DevIconSwift'               , sel_bg}},
            DevIconKsh                  = {'', {'DevIconKsh'                 , sel_bg}},
            DevIconLess                 = {'', {'DevIconLess'                , sel_bg}},
            DevIconGitModules           = {'', {'DevIconGitModules'          , sel_bg}},
            DevIconGemspec              = {'', {'DevIconGemspec'             , sel_bg}},
            DevIconStyl                 = {'', {'DevIconStyl'                , sel_bg}},
            DevIconBmp                  = {'', {'DevIconBmp'                 , sel_bg}},
            DevIconGodotProject         = {'', {'DevIconGodotProject'        , sel_bg}},
            DevIconLhs                  = {'', {'DevIconLhs'                 , sel_bg}},
            DevIconD                    = {'', {'DevIconD'                   , sel_bg}},
            DevIconVim                  = {'', {'DevIconVim'                 , sel_bg}},
            DevIconScala                = {'', {'DevIconScala'               , sel_bg}},
            DevIconTerminal             = {'', {'DevIconTerminal'            , sel_bg}},
            DevIconGemfile              = {'', {'DevIconGemfile'             , sel_bg}},
            DevIconClojureC             = {'', {'DevIconClojureC'            , sel_bg}},
            DevIconFsx                  = {'', {'DevIconFsx'                 , sel_bg}},
            DevIconTs                   = {'', {'DevIconTs'                  , sel_bg}},
            DevIconHpp                  = {'', {'DevIconHpp'                 , sel_bg}},
            DevIconRlib                 = {'', {'DevIconRlib'                , sel_bg}},
            DevIconCoffee               = {'', {'DevIconCoffee'              , sel_bg}},
            DevIconLicense              = {'', {'DevIconLicense'             , sel_bg}},
            DevIconAi                   = {'', {'DevIconAi'                  , sel_bg}},
            DevIconGitAttributes        = {'', {'DevIconGitAttributes'       , sel_bg}},
            DevIconBashProfile          = {'', {'DevIconBashProfile'         , sel_bg}},
            DevIconSolidity             = {'', {'DevIconSolidity'            , sel_bg}},
            DevIconVagrantfile          = {'', {'DevIconVagrantfile'         , sel_bg}},
            DevIconToml                 = {'', {'DevIconToml'                , sel_bg}},
            DevIconDockerfile           = {'', {'DevIconDockerfile'          , sel_bg}},
            DevIconFsharp               = {'', {'DevIconFsharp'              , sel_bg}},
            DevIconClojureDart          = {'', {'DevIconClojureDart'         , sel_bg}},
            DevIconHaml                 = {'', {'DevIconHaml'                , sel_bg}},
            DevIconNPMIgnore            = {'', {'DevIconNPMIgnore'           , sel_bg}},
            DevIconConfiguration        = {'', {'DevIconConfiguration'       , sel_bg}},
            DevIconEex                  = {'', {'DevIconEex'                 , sel_bg}},
            DevIconErb                  = {'', {'DevIconErb'                 , sel_bg}},
            DevIconXls                  = {'', {'DevIconXls'                 , sel_bg}},
            DevIconAwk                  = {'', {'DevIconAwk'                 , sel_bg}},
            DevIconYml                  = {'', {'DevIconYml'                 , sel_bg}},
            DevIconXml                  = {'', {'DevIconXml'                 , sel_bg}},
            DevIconNix                  = {'', {'DevIconNix'                 , sel_bg}},
            DevIconGvimrc               = {'', {'DevIconGvimrc'              , sel_bg}},
            DevIconErl                  = {'', {'DevIconErl'                 , sel_bg}},
            DevIconClojureJS            = {'', {'DevIconClojureJS'           , sel_bg}},
            DevIconRs                   = {'', {'DevIconRs'                  , sel_bg}},
            DevIconPhp                  = {'', {'DevIconPhp'                 , sel_bg}},
            DevIconTwig                 = {'', {'DevIconTwig'                , sel_bg}},
            DevIconMjs                  = {'', {'DevIconMjs'                 , sel_bg}},
            DevIconSml                  = {'', {'DevIconSml'                 , sel_bg}},
            DevIconSlim                 = {'', {'DevIconSlim'                , sel_bg}},
            DevIconHeex                 = {'', {'DevIconHeex'                , sel_bg}},
            DevIconMdx                  = {'', {'DevIconMdx'                 , sel_bg}},
            DevIconFs                   = {'', {'DevIconFs'                  , sel_bg}},
            DevIconCson                 = {'', {'DevIconCson'                , sel_bg}},
            DevIconDsStore              = {'', {'DevIconDsStore'             , sel_bg}},
            DevIconPromptPs1           =    {'', {'', 'c4'}},
            DevIconMotoko               = {'', {'DevIconMotoko'              , sel_bg}},
            DevIconMixLock              = {'', {'DevIconMixLock'             , sel_bg}},
            DevIconDropbox              = {'', {'DevIconDropbox'             , sel_bg}},
            DevIconProlog               = {'', {'DevIconProlog'              , sel_bg}},
            DevIconH                    = {'', {'DevIconH'                   , sel_bg}},
            DevIconRss                  = {'', {'DevIconRss'                 , sel_bg}},
            DevIconCs                   = {'', {'DevIconCs'                  , sel_bg}},
            DevIconExs                  = {'', {'DevIconExs'                 , sel_bg}},
            DevIconFavicon              = {'', {'DevIconFavicon'             , sel_bg}},
            DevIconBat                  = {'', {'DevIconBat'                 , sel_bg}},
            DevIconDrools               = {'', {'DevIconDrools'              , sel_bg}},
            DevIconJs                   = {'', {'DevIconJs'                  , sel_bg}},
            DevIconVue                  = {'', {'DevIconVue'                 , sel_bg}},
            DevIconHs                   = {'', {'DevIconHs'                  , sel_bg}},
            DevIconPng                  = {'', {'DevIconPng'                 , sel_bg}},
            DevIconPm                   = {'', {'DevIconPm'                  , sel_bg}},
            DevIconBinaryGLTF           = {'', {'DevIconBinaryGLTF'          , sel_bg}},
            DevIconRproj                = {'', {'DevIconRproj'               , sel_bg}},
            DevIconDump                 = {'', {'DevIconDump'                , sel_bg}},
            DevIconDb                   = {'', {'DevIconDb'                  , sel_bg}},
            DevIconCss                  = {'', {'DevIconCss'                 , sel_bg}},
            DevIconPy                   = {'', {'DevIconPy'                  , sel_bg}},
            DevIconPsb                  = {'', {'DevIconPsb'                 , sel_bg}},
            DevIconTextResource         = {'', {'DevIconTextResource'        , sel_bg}},
            DevIconSettingsJson         = {'', {'DevIconSettingsJson'        , sel_bg}},
            DevIconPl                   = {'', {'DevIconPl'                  , sel_bg}},
            DevIconConfigRu             = {'', {'DevIconConfigRu'            , sel_bg}},
            DevIconNim                  = {'', {'DevIconNim'                 , sel_bg}},
            DevIconConf                 = {'', {'DevIconConf'                , sel_bg}},
            DevIconRake                 = {'', {'DevIconRake'                , sel_bg}},
            DevIconWebmanifest          = {'', {'DevIconWebmanifest'         , sel_bg}},
            DevIconOpenTypeFont         = {'', {'DevIconOpenTypeFont'        , sel_bg}},
            DevIconClojure              = {'', {'DevIconClojure'             , sel_bg}},
            DevIconMaterial             = {'', {'DevIconMaterial'            , sel_bg}},
            DevIconCxx                  = {'', {'DevIconCxx'                 , sel_bg}},
            DevIconVHDL                 = {'', {'DevIconVHDL'                , sel_bg}},
            DevIconLeex                 = {'', {'DevIconLeex'                , sel_bg}},
            DevIconMint                 = {'', {'DevIconMint'                , sel_bg}},
            DevIconMustache             = {'', {'DevIconMustache'            , sel_bg}},
            DevIconNodeModules          = {'', {'DevIconNodeModules'         , sel_bg}},
            DevIconOPUS                 = {'', {'DevIconOPUS'                , sel_bg}},
            DevIconBash                 = {'', {'DevIconBash'                , sel_bg}},
            DevIconZshprofile           = {'', {'DevIconZshprofile'          , sel_bg}},
            DevIconWebp                 = {'', {'DevIconWebp'                , sel_bg}},
            DevIconGDScript             = {'', {'DevIconGDScript'            , sel_bg}},
            DevIconGitIgnore            = {'', {'DevIconGitIgnore'           , sel_bg}},
            DevIconPsd                  = {'', {'DevIconPsd'                 , sel_bg}},
            DevIconBabelrc              = {'', {'DevIconBabelrc'             , sel_bg}},
            DevIconHrl                  = {'', {'DevIconHrl'                 , sel_bg}},
            DevIconPdf                  = {'', {'DevIconPdf'                 , sel_bg}},
            DevIconPpt                  = {'', {'DevIconPpt'                 , sel_bg}},
            DevIconRb                   = {'', {'DevIconRb'                  , sel_bg}},
            DevIconGitlabCI             = {'', {'DevIconGitlabCI'            , sel_bg}},
            DevIconRakefile             = {'', {'DevIconRakefile'            , sel_bg}},
            DevIconBashrc               = {'', {'DevIconBashrc'              , sel_bg}},
            DevIconWebpack              = {'', {'DevIconWebpack'             , sel_bg}},
            DevIconGulpfile             = {'', {'DevIconGulpfile'            , sel_bg}},
            DevIconSuo                  = {'', {'DevIconSuo'                 , sel_bg}},
            DevIconMakefile             = {'', {'DevIconMakefile'            , sel_bg}},
            DevIconHh                   = {'', {'DevIconHh'                  , sel_bg}},
            DevIconCsv                  = {'', {'DevIconCsv'                 , sel_bg}},
            DevIconPyo                  = {'', {'DevIconPyo'                 , sel_bg}},
            DevIconNPMrc                = {'', {'DevIconNPMrc'               , sel_bg}},
            DevIconMd                   = {'', {'DevIconMd'                  , sel_bg}},
            DevIconTextScene            = {'', {'DevIconTextScene'           , sel_bg}},
            DevIconCsh                  = {'', {'DevIconCsh'                 , sel_bg}},
            DevIconFish                 = {'', {'DevIconFish'                , sel_bg}},
            DevIconCMakeLists           = {'', {'DevIconCMakeLists'          , sel_bg}},
            DevIconFsi                  = {'', {'DevIconFsi'                 , sel_bg}},
            DevIconTor                  = {'', {'DevIconTor'                 , sel_bg}},
            DevIconEdn                  = {'', {'DevIconEdn'                 , sel_bg}},
            DevIconPackedResource       = {'', {'DevIconPackedResource'      , sel_bg}},
            DevIconSh                   = {'', {'DevIconSh'                  , sel_bg}},
            DevIconFennel               = {'', {'DevIconFennel'              , sel_bg}},
            DevIconHbs                  = {'', {'DevIconHbs'                 , sel_bg}},
            DevIconPyd                  = {'', {'DevIconPyd'                 , sel_bg}},
            DevIconTsx                  = {'', {'DevIconTsx'                 , sel_bg}},
            DevIconDiff_inactive                 = {'', {'DevIconDiff'                , norm_bg}},
            DevIconElm_inactive                  = {'', {'DevIconElm'                 , norm_bg}},
            DevIconJl_inactive                   = {'', {'DevIconJl'                  , norm_bg}},
            DevIconSass_inactive                 = {'', {'DevIconSass'                , norm_bg}},
            DevIconXcPlayground_inactive         = {'', {'DevIconXcPlayground'        , norm_bg}},
            DevIconSln_inactive                  = {'', {'DevIconSln'                 , norm_bg}},
            DevIconTxt_inactive                  = {'', {'DevIconTxt'                 , norm_bg}},
            DevIconTcl_inactive                  = {'', {'DevIconTcl'                 , norm_bg}},
            DevIconR_inactive                    = {'', {'DevIconR'                   , norm_bg}},
            DevIconZshrc_inactive                = {'', {'DevIconZshrc'               , norm_bg}},
            DevIconTex_inactive                  = {'', {'DevIconTex'                 , norm_bg}},
            DevIconLua_inactive                  = {'', {'DevIconLua'                 , norm_bg}},
            DevIconJsx_inactive                  = {'', {'DevIconJsx'                 , norm_bg}},
            DevIconJson_inactive                 = {'', {'DevIconJson'                , norm_bg}},
            DevIconGif_inactive                  = {'', {'DevIconGif'                 , norm_bg}},
            DevIconMl_inactive                   = {'', {'DevIconMl'                  , norm_bg}},
            DevIconMarkdown_inactive             = {'', {'DevIconMarkdown'            , norm_bg}},
            DevIconCp_inactive                   = {'', {'DevIconCp'                  , norm_bg}},
            DevIconRmd_inactive                  = {'', {'DevIconRmd'                 , norm_bg}},
            DevIconBrewfile_inactive             = {'', {'DevIconBrewfile'            , norm_bg}},
            DevIconZsh_inactive                  = {'', {'DevIconZsh'                 , norm_bg}},
            DevIconVerilog_inactive              = {'', {'DevIconVerilog'             , norm_bg}},
            DevIconCrystal_inactive              = {'', {'DevIconCrystal'             , norm_bg}},
            DevIconJpg_inactive                  = {'', {'DevIconJpg'                 , norm_bg}},
            DevIconSystemVerilog_inactive        = {'', {'DevIconSystemVerilog'       , norm_bg}},
            DevIconPyc_inactive                  = {'', {'DevIconPyc'                 , norm_bg}},
            DevIconGitCommit_inactive            = {'', {'DevIconGitCommit'           , norm_bg}},
            DevIconIco_inactive                  = {'', {'DevIconIco'                 , norm_bg}},
            DevIconProcfile_inactive             = {'', {'DevIconProcfile'            , norm_bg}},
            DevIconDesktopEntry_inactive         = {'', {'DevIconDesktopEntry'        , norm_bg}},
            DevIconFsscript_inactive             = {'', {'DevIconFsscript'            , norm_bg}},
            DevIconKotlin_inactive               = {'', {'DevIconKotlin'              , norm_bg}},
            DevIconSig_inactive                  = {'', {'DevIconSig'                 , norm_bg}},
            DevIconZig_inactive                  = {'', {'DevIconZig'                 , norm_bg}},
            DevIconKotlinScript_inactive         = {'', {'DevIconKotlinScript'        , norm_bg}},
            DevIconEx_inactive                   = {'', {'DevIconEx'                  , norm_bg}},
            DevIconMli_inactive                  = {'', {'DevIconMli'                 , norm_bg}},
            DevIconSvelte_inactive               = {'', {'DevIconSvelte'              , norm_bg}},
            DevIconSql_inactive                  = {'', {'DevIconSql'                 , norm_bg}},
            DevIconC_inactive                    = {'', {'DevIconC'                   , norm_bg}},
            DevIconEjs_inactive                  = {'', {'DevIconEjs'                 , norm_bg}},
            DevIconJava_inactive                 = {'', {'DevIconJava'                , norm_bg}},
            DevIconGruntfile_inactive            = {'', {'DevIconGruntfile'           , norm_bg}},
            DevIconSvg_inactive                  = {'', {'DevIconSvg'                 , norm_bg}},
            DevIconXul_inactive                  = {'', {'DevIconXul'                 , norm_bg}},
            DevIconDart_inactive                 = {'', {'DevIconDart'                , norm_bg}},
            DevIconCMake_inactive                = {'', {'DevIconCMake'               , norm_bg}},
            DevIconZshenv_inactive               = {'', {'DevIconZshenv'              , norm_bg}},
            DevIconHxx_inactive                  = {'', {'DevIconHxx'                 , norm_bg}},
            DevIconYaml_inactive                 = {'', {'DevIconYaml'                , norm_bg}},
            DevIconCobol_inactive                = {'', {'DevIconCobol'               , norm_bg}},
            DevIconCPlusPlus_inactive            = {'', {'DevIconCPlusPlus'           , norm_bg}},
            DevIconDefault_inactive              = {'', {'DevIconDefault'             , norm_bg}},
            DevIconGo_inactive                   = {'', {'DevIconGo'                  , norm_bg}},
            DevIconGitLogo_inactive              = {'', {'DevIconGitLogo'             , norm_bg}},
            DevIconJpeg_inactive                 = {'', {'DevIconJpeg'                , norm_bg}},
            DevIconVimrc_inactive                = {'', {'DevIconVimrc'               , norm_bg}},
            DevIconHtml_inactive                 = {'', {'DevIconHtml'                , norm_bg}},
            DevIconIni_inactive                  = {'', {'DevIconIni'                 , norm_bg}},
            DevIconCpp_inactive                  = {'', {'DevIconCpp'                 , norm_bg}},
            DevIconHtm_inactive                  = {'', {'DevIconHtm'                 , norm_bg}},
            DevIconDoc_inactive                  = {'', {'DevIconDoc'                 , norm_bg}},
            DevIconScss_inactive                 = {'', {'DevIconScss'                , norm_bg}},
            DevIconGitConfig_inactive            = {'', {'DevIconGitConfig'           , norm_bg}},
            DevIconSwift_inactive                = {'', {'DevIconSwift'               , norm_bg}},
            DevIconKsh_inactive                  = {'', {'DevIconKsh'                 , norm_bg}},
            DevIconLess_inactive                 = {'', {'DevIconLess'                , norm_bg}},
            DevIconGitModules_inactive           = {'', {'DevIconGitModules'          , norm_bg}},
            DevIconGemspec_inactive              = {'', {'DevIconGemspec'             , norm_bg}},
            DevIconStyl_inactive                 = {'', {'DevIconStyl'                , norm_bg}},
            DevIconBmp_inactive                  = {'', {'DevIconBmp'                 , norm_bg}},
            DevIconGodotProject_inactive         = {'', {'DevIconGodotProject'        , norm_bg}},
            DevIconLhs_inactive                  = {'', {'DevIconLhs'                 , norm_bg}},
            DevIconD_inactive                    = {'', {'DevIconD'                   , norm_bg}},
            DevIconVim_inactive                  = {'', {'DevIconVim'                 , norm_bg}},
            DevIconScala_inactive                = {'', {'DevIconScala'               , norm_bg}},
            DevIconTerminal_inactive             = {'', {'DevIconTerminal'            , norm_bg}},
            DevIconGemfile_inactive              = {'', {'DevIconGemfile'             , norm_bg}},
            DevIconClojureC_inactive             = {'', {'DevIconClojureC'            , norm_bg}},
            DevIconFsx_inactive                  = {'', {'DevIconFsx'                 , norm_bg}},
            DevIconTs_inactive                   = {'', {'DevIconTs'                  , norm_bg}},
            DevIconHpp_inactive                  = {'', {'DevIconHpp'                 , norm_bg}},
            DevIconRlib_inactive                 = {'', {'DevIconRlib'                , norm_bg}},
            DevIconCoffee_inactive               = {'', {'DevIconCoffee'              , norm_bg}},
            DevIconLicense_inactive              = {'', {'DevIconLicense'             , norm_bg}},
            DevIconAi_inactive                   = {'', {'DevIconAi'                  , norm_bg}},
            DevIconGitAttributes_inactive        = {'', {'DevIconGitAttributes'       , norm_bg}},
            DevIconBashProfile_inactive          = {'', {'DevIconBashProfile'         , norm_bg}},
            DevIconSolidity_inactive             = {'', {'DevIconSolidity'            , norm_bg}},
            DevIconVagrantfile_inactive          = {'', {'DevIconVagrantfile'         , norm_bg}},
            DevIconToml_inactive                 = {'', {'DevIconToml'                , norm_bg}},
            DevIconDockerfile_inactive           = {'', {'DevIconDockerfile'          , norm_bg}},
            DevIconFsharp_inactive               = {'', {'DevIconFsharp'              , norm_bg}},
            DevIconClojureDart_inactive          = {'', {'DevIconClojureDart'         , norm_bg}},
            DevIconHaml_inactive                 = {'', {'DevIconHaml'                , norm_bg}},
            DevIconNPMIgnore_inactive            = {'', {'DevIconNPMIgnore'           , norm_bg}},
            DevIconConfiguration_inactive        = {'', {'DevIconConfiguration'       , norm_bg}},
            DevIconEex_inactive                  = {'', {'DevIconEex'                 , norm_bg}},
            DevIconErb_inactive                  = {'', {'DevIconErb'                 , norm_bg}},
            DevIconXls_inactive                  = {'', {'DevIconXls'                 , norm_bg}},
            DevIconAwk_inactive                  = {'', {'DevIconAwk'                 , norm_bg}},
            DevIconYml_inactive                  = {'', {'DevIconYml'                 , norm_bg}},
            DevIconXml_inactive                  = {'', {'DevIconXml'                 , norm_bg}},
            DevIconNix_inactive                  = {'', {'DevIconNix'                 , norm_bg}},
            DevIconGvimrc_inactive               = {'', {'DevIconGvimrc'              , norm_bg}},
            DevIconErl_inactive                  = {'', {'DevIconErl'                 , norm_bg}},
            DevIconClojureJS_inactive            = {'', {'DevIconClojureJS'           , norm_bg}},
            DevIconRs_inactive                   = {'', {'DevIconRs'                  , norm_bg}},
            DevIconPhp_inactive                  = {'', {'DevIconPhp'                 , norm_bg}},
            DevIconTwig_inactive                 = {'', {'DevIconTwig'                , norm_bg}},
            DevIconMjs_inactive                  = {'', {'DevIconMjs'                 , norm_bg}},
            DevIconSml_inactive                  = {'', {'DevIconSml'                 , norm_bg}},
            DevIconSlim_inactive                 = {'', {'DevIconSlim'                , norm_bg}},
            DevIconHeex_inactive                 = {'', {'DevIconHeex'                , norm_bg}},
            DevIconMdx_inactive                  = {'', {'DevIconMdx'                 , norm_bg}},
            DevIconFs_inactive                   = {'', {'DevIconFs'                  , norm_bg}},
            DevIconCson_inactive                 = {'', {'DevIconCson'                , norm_bg}},
            DevIconDsStore_inactive              = {'', {'DevIconDsStore'             , norm_bg}},
            DevIconPromptPs_inactive1           =    {'', {'', 'c4'}},
            DevIconMotoko_inactive               = {'', {'DevIconMotoko'              , norm_bg}},
            DevIconMixLock_inactive              = {'', {'DevIconMixLock'             , norm_bg}},
            DevIconDropbox_inactive              = {'', {'DevIconDropbox'             , norm_bg}},
            DevIconProlog_inactive               = {'', {'DevIconProlog'              , norm_bg}},
            DevIconH_inactive                    = {'', {'DevIconH'                   , norm_bg}},
            DevIconRss_inactive                  = {'', {'DevIconRss'                 , norm_bg}},
            DevIconCs_inactive                   = {'', {'DevIconCs'                  , norm_bg}},
            DevIconExs_inactive                  = {'', {'DevIconExs'                 , norm_bg}},
            DevIconFavicon_inactive              = {'', {'DevIconFavicon'             , norm_bg}},
            DevIconBat_inactive                  = {'', {'DevIconBat'                 , norm_bg}},
            DevIconDrools_inactive               = {'', {'DevIconDrools'              , norm_bg}},
            DevIconJs_inactive                   = {'', {'DevIconJs'                  , norm_bg}},
            DevIconVue_inactive                  = {'', {'DevIconVue'                 , norm_bg}},
            DevIconHs_inactive                   = {'', {'DevIconHs'                  , norm_bg}},
            DevIconPng_inactive                  = {'', {'DevIconPng'                 , norm_bg}},
            DevIconPm_inactive                   = {'', {'DevIconPm'                  , norm_bg}},
            DevIconBinaryGLTF_inactive           = {'', {'DevIconBinaryGLTF'          , norm_bg}},
            DevIconRproj_inactive                = {'', {'DevIconRproj'               , norm_bg}},
            DevIconDump_inactive                 = {'', {'DevIconDump'                , norm_bg}},
            DevIconDb_inactive                   = {'', {'DevIconDb'                  , norm_bg}},
            DevIconCss_inactive                  = {'', {'DevIconCss'                 , norm_bg}},
            DevIconPy_inactive                   = {'', {'DevIconPy'                  , norm_bg}},
            DevIconPsb_inactive                  = {'', {'DevIconPsb'                 , norm_bg}},
            DevIconTextResource_inactive         = {'', {'DevIconTextResource'        , norm_bg}},
            DevIconSettingsJson_inactive         = {'', {'DevIconSettingsJson'        , norm_bg}},
            DevIconPl_inactive                   = {'', {'DevIconPl'                  , norm_bg}},
            DevIconConfigRu_inactive             = {'', {'DevIconConfigRu'            , norm_bg}},
            DevIconNim_inactive                  = {'', {'DevIconNim'                 , norm_bg}},
            DevIconConf_inactive                 = {'', {'DevIconConf'                , norm_bg}},
            DevIconRake_inactive                 = {'', {'DevIconRake'                , norm_bg}},
            DevIconWebmanifest_inactive          = {'', {'DevIconWebmanifest'         , norm_bg}},
            DevIconOpenTypeFont_inactive         = {'', {'DevIconOpenTypeFont'        , norm_bg}},
            DevIconClojure_inactive              = {'', {'DevIconClojure'             , norm_bg}},
            DevIconMaterial_inactive             = {'', {'DevIconMaterial'            , norm_bg}},
            DevIconCxx_inactive                  = {'', {'DevIconCxx'                 , norm_bg}},
            DevIconVHDL_inactive                 = {'', {'DevIconVHDL'                , norm_bg}},
            DevIconLeex_inactive                 = {'', {'DevIconLeex'                , norm_bg}},
            DevIconMint_inactive                 = {'', {'DevIconMint'                , norm_bg}},
            DevIconMustache_inactive             = {'', {'DevIconMustache'            , norm_bg}},
            DevIconNodeModules_inactive          = {'', {'DevIconNodeModules'         , norm_bg}},
            DevIconOPUS_inactive                 = {'', {'DevIconOPUS'                , norm_bg}},
            DevIconBash_inactive                 = {'', {'DevIconBash'                , norm_bg}},
            DevIconZshprofile_inactive           = {'', {'DevIconZshprofile'          , norm_bg}},
            DevIconWebp_inactive                 = {'', {'DevIconWebp'                , norm_bg}},
            DevIconGDScript_inactive             = {'', {'DevIconGDScript'            , norm_bg}},
            DevIconGitIgnore_inactive            = {'', {'DevIconGitIgnore'           , norm_bg}},
            DevIconPsd_inactive                  = {'', {'DevIconPsd'                 , norm_bg}},
            DevIconBabelrc_inactive              = {'', {'DevIconBabelrc'             , norm_bg}},
            DevIconHrl_inactive                  = {'', {'DevIconHrl'                 , norm_bg}},
            DevIconPdf_inactive                  = {'', {'DevIconPdf'                 , norm_bg}},
            DevIconPpt_inactive                  = {'', {'DevIconPpt'                 , norm_bg}},
            DevIconRb_inactive                   = {'', {'DevIconRb'                  , norm_bg}},
            DevIconGitlabCI_inactive             = {'', {'DevIconGitlabCI'            , norm_bg}},
            DevIconRakefile_inactive             = {'', {'DevIconRakefile'            , norm_bg}},
            DevIconBashrc_inactive               = {'', {'DevIconBashrc'              , norm_bg}},
            DevIconWebpack_inactive              = {'', {'DevIconWebpack'             , norm_bg}},
            DevIconGulpfile_inactive             = {'', {'DevIconGulpfile'            , norm_bg}},
            DevIconSuo_inactive                  = {'', {'DevIconSuo'                 , norm_bg}},
            DevIconMakefile_inactive             = {'', {'DevIconMakefile'            , norm_bg}},
            DevIconHh_inactive                   = {'', {'DevIconHh'                  , norm_bg}},
            DevIconCsv_inactive                  = {'', {'DevIconCsv'                 , norm_bg}},
            DevIconPyo_inactive                  = {'', {'DevIconPyo'                 , norm_bg}},
            DevIconNPMrc_inactive                = {'', {'DevIconNPMrc'               , norm_bg}},
            DevIconMd_inactive                   = {'', {'DevIconMd'                  , norm_bg}},
            DevIconTextScene_inactive            = {'', {'DevIconTextScene'           , norm_bg}},
            DevIconCsh_inactive                  = {'', {'DevIconCsh'                 , norm_bg}},
            DevIconFish_inactive                 = {'', {'DevIconFish'                , norm_bg}},
            DevIconCMakeLists_inactive           = {'', {'DevIconCMakeLists'          , norm_bg}},
            DevIconFsi_inactive                  = {'', {'DevIconFsi'                 , norm_bg}},
            DevIconTor_inactive                  = {'', {'DevIconTor'                 , norm_bg}},
            DevIconEdn_inactive                  = {'', {'DevIconEdn'                 , norm_bg}},
            DevIconPackedResource_inactive       = {'', {'DevIconPackedResource'      , norm_bg}},
            DevIconSh_inactive                   = {'', {'DevIconSh'                  , norm_bg}},
            DevIconFennel_inactive               = {'', {'DevIconFennel'              , norm_bg}},
            DevIconHbs_inactive                  = {'', {'DevIconHbs'                 , norm_bg}},
            DevIconPyd_inactive                  = {'', {'DevIconPyd'                 , norm_bg}},
            DevIconTsx_inactive                  = {'', {'DevIconTsx'                 , norm_bg}},
            normal        = {'GUH..'                             , {norm_fg, norm_bg}},
            normal_start  = {' '                           , {norm_bg, bg}},
            normal_end    = {'' .. ''                    , {norm_bg, bg}},
            -- normal_last display if tab is the last tab
            normal_last   = {' '        , {norm_bg , bg}},


            -- this only use a highlight color a text will replace by tab name
            select        = {'GWAA'                             , {sel_fg, sel_bg}},
            select_start  = {' '                           , {sel_bg, bg}},
            select_end    = {' '                     , {sel_bg, bg}},
            -- select_last display if select tab is a last tab
            select_last   = {' '        , {sel_bg , bg}},

            -- normal_select display if a next tab is select
            normal_select = {' '        , {norm_bg , bg}},
         },
      }
   })

end

return M
