#!/usr/bin/env bash

WORKSPACES=7 # make this number the amount of workspaces you want to display

wspaces=$(wmctrl -d | head -$WORKSPACES | grep -o "[0-9]  [-\*]" | rev | tr '\n' ' ')
wspaces=${wspaces/0/Ѐ}
wspaces=${wspaces/1/Ѕ}
wspaces=${wspaces/2/Є}
wspaces=${wspaces/3/Ё}
wspaces=${wspaces/4/Ђ}
wspaces=${wspaces/5/Ѓ}
wspaces=${wspaces/6/І}
wspaces=${wspaces//-/%\{F#5AF78E\}}
wspaces=${wspaces/\*/%\{F#FFB526\}}
echo $wspaces

