#!/bin/bash

if [ "$1" = "mpvrun" ]
then
   mpv -vo x11 --wid="$2" --mute --loop=inf -hwdec=no --no-osc "$3" &> /dev/null
   exit
fi

trap "walc r && killall mpv" INT HUP TERM

#get random wall
getrand(){
	wall=$(ls "$2" | sort -R |tail -1)
    wall="$2"/"$wall"
    echo "$wall" > ~/wallp/animcurrent
}

#read in last wall
restore(){
    read -r wall < ~/wallp/animcurrent
}

#manually select an image
manual(){
    wall=$(readlink -f "$1")
    echo "$wall" > ~/wallp/animcurrent
}

#set wall
setwall(){
   pkill mpv &>/dev/null
   sleep .1
	xwinwrap -ov -fs -- $0 "mpvrun" WID "$wall" &>/dev/null
}


if [ "$1" = "z" ]
then
    getrand "$@" && setwall

elif [ "$1" = "r" ] 
then
    restore && setwall

elif [ "$1" = "s" ] 
then
    pkill mpv && walc r

else
    manual "$@" && setwall &
fi
