#!/bin/bash

trap "walc r && killall mpv" INT HUP TERM

#get random wall
getrand(){
	wall=$(ls "$2" | sort -R |tail -1)
    wall="$2"/"$wall"
    echo "$wall" > ~/wallp/animcurrent
}

#read in last wall
restore(){
    read -r wall < ~/wallp/animcurrent
}

#manually select an image
manual(){
    wall=$(readlink -f "$1")
    echo "$wall" > ~/wallp/animcurrent
}

#set wall
setwall(){
   pkill mpv &>/dev/null
   sleep .1
	xwinwrap -ov -fs -- mpv -vo x11 --wid WID --mute --loop=inf -hwdec=no --no-osc "$wall" 1>/dev/null &>/dev/null & disown
}


if [ "$1" = "z" ]
then
    getrand "$@" && setwall

elif [ "$1" = "r" ] 
then
    restore && setwall

else
    manual "$@" && setwall
fi
