#!/bin/sh


killall mpv
if [ "$1" = "z" ]
	#Wallpaper randomization
	then
		randomwall=$(ls ~/wallp/animwalls | sort -R |tail -1)
		mpv --wid=0 --mute --loop=inf --video-unscaled=yes "/home/zoe/wallp/animwalls/$randomwall"
		echo "$randomwall" > ~/wallp/animcurrent
	
	#Wallpaper Restore
	elif [ $1 = "r" ]
	then
		read -r lastwall < ~/wallp/animcurrent
			mpv --wid=0 --mute --loop=inf --video-unscaled=yes "/home/zoe/wallp/animwalls/$lastwall"
	
	#Set locker background
	elif [ $1 = "l" ]
	then
		read -r lastwall < /home/zoe/wallp/current
		cp /home/zoe/wallp/walls/$lastwall /locker.png
		echo $lastwall
	#Set wallpaper
	else
		mpv --wid=0 --mute --loop=inf --video-unscaled=yes "$1"
		echo "$1" > ~/wallp/animcurrent
fi

