#!/bin/sh

#wallpaper directory
walldir="$HOME/wallp/walls"

getrand(){
	#Wallpaper randomization
    wall=$(find "$walldir" -name "*.*g" | sort -R | tail -1)
    echo "$wall" > "$walldir/current"
}

restore(){
	#Wallpaper Restore
    read -r wall < "$walldir/current"
}

manual(){
    #set specified image
    wall=$(readlink -f "$1")
    echo "$wall" > "$walldir/current"
}

search(){
    #search wallpaper dir, requires fzf
    dir="$(pwd)"
    cd "$walldir"
    wall=$(fzf)
    wall="$walldir/$wall"
    echo "$wall" > "$walldir/current"

}

setwall(){
    #set wallpaper to provided image
    feh --bg-fill "$wall"
}

if [ "$1" = "z" ] #random wallpaper
then
    getrand "$2"
    setwall
elif [ "$1" = "r" ] #restore last wallpaper
then
    restore
    setwall
elif [ "$1" = "s" ]
then
    search
    setwall
else
    manual "$1" #set $1 as wallpaper
    setwall
fi
