#!/bin/bash

memtotal=$(free | tail -2 | head -1 | xargs | cut -d ' ' -f 2)

##########
# volume #
##########
vol(){
   while true; do
      cat /tmp/dacvol | xargs printf "%%{cT1}%d %%{T2}\n"
   done
}


###########
# battery #
###########
bat(){
   while true; do
      read bat < "/sys/class/power_supply/BAT0/capacity"
      printf "%%{c}%d \n" $bat
      sleep 2
   done
}


###############
# date + time #
###############
datetime(){
   while true; do
      date +"%%{c}%H//%M   %m//%d " 
      sleep 3
   done
}

mem(){
   while true; do
      memuse=$(free | tail -2 | head -1 | xargs | cut -d ' ' -f 3)
      printf "%%{cT1}%.0f%%{T2} \n" $(bc -l <<< "$memuse*((100.0)/$memtotal)")
      sleep 2
   done
}

##############
# workspaces #
##############
herbspaces2(){
WORKSPACES=7 # make this number the amount of workspaces you want to display
read yellow < /home/zoe/.config/ricer/ricer/ricer/ricertemplates/colors/base10
read green < /home/zoe/.config/ricer/ricer/ricer/ricertemplates/colors/base11

getinfo(){
    wspaces=$(wmctrl -d | head -$workspaces | grep -o "[0-9]  [-\*]" | rev | tr '\n' ' ' | cut -d '-' -f 1-7)
}


format(){
    echo "$wspaces" | sed\
        -e 's/0//'\
        -e 's/1//'\
        -e 's/2//'\
        -e 's/3//'\
        -e 's/4//'\
        -e 's/5//'\
        -e 's/6//'\
        -e "s/\-/%\{F#$orange\}/g"\
        -e "s/\*  /  %\{F#$green\}/g"
    }

change(){
    cat < /tmp/herbchange
}

mkfifo /tmp/herbchange
while true;
do
    getinfo
    format
    change
done
}

################
# bar settings #
################
read red < /home/zoe/.config/ricer/ricertemplates/colors/base8
read orange < /home/zoe/.config/ricer/ricertemplates/colors/base9
read yellow < /home/zoe/.config/ricer/ricertemplates/colors/base10
read green < /home/zoe/.config/ricer/ricertemplates/colors/base11
read lblue < /home/zoe/.config/ricer/ricertemplates/colors/base12
read blue < /home/zoe/.config/ricer/ricertemplates/colors/base13
read brown < /home/zoe/.config/ricer/ricertemplates/colors/base14
read background < /home/zoe/.config/ricer/ricertemplates/colors/base0
read background2 < /home/zoe/.config/ricer/ricertemplates/colors/base4
font="Aerolite Bold:size=14:style=Medium"
icons1="Font Awesome 5 Free Solid:size=9"
icons2="Symbols Nerd Font:size=12"
icons3="Symbols Nerd Font:size=10"
icons4="Font Awesome 5 Free:size=11"
echo $background IS TEST COLOR
trap "kill %1; kill %2; kill %3; kill %4; kill %5" SIGINT SIGTERM


################
# DISPLAY BARS #
################
#bkg
echo | lemonbar -d -B "#$background2" -g 170x58+0+1022 -p &
echo | lemonbar -d -B "#$background2" -g 308x38+0+1042 -p &
echo | lemonbar -d -B "#$background2" -g 100x38+1820+1042 -p &
sleep .1
echo | lemonbar -d -B "#$background" -g 100x20+0+1030 -p &
sleep .3
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=20" -g 155x30+170+1022 -F "#$background2" &
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=25" -g 155x40+307+1040 -F "#$background2" &
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=25" -g 55x40+1784+1040 -F "#$background2" &
sleep .3
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=20" -g 155x30+170+1031 -F "#$background" &
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=18" -g 155x30+300+1050 -F "#$background" &
echo  | lemonbar -d -p -f "Powerline Extra Symbols:size=18" -g 55x30+1804+1050 -F "#$background" &
sleep .1
echo | lemonbar -d -B "#$background" -g 300x30+0+1050 -p &


#workspaces
herbspaces2 | lemonbar -d -o 1 -f "$icons1" -o 2 -f "$icons3" -g 165x20+5+1030 -B"#$background" &

#volume
vol | lemonbar -d -o 0 -f "$font" -o 1 -f "$icons2" -g 46x20+15+1055 -B"#$background" -F"#$orange" &

#date
datetime | lemonbar -d -o 0 -f "$font" -o 1 -f "$icons2" -g 150x20+140+1055 -B"#$background" -F"#$orange" &

#battery
bat | lemonbar -d -p -o 0 -f "$font" -o 1 -f "$icons2" -g 64x20+70+1055 -B"#$background" -F"#$orange" &

#mem
mem | lemonbar -d -p -o 0 -f "$font" -o -2 -f "$font" -f "$icons2" -g 90x30+1830+1050 -B"#$background" -F"#$orange" 
